# -*- coding: utf-8 -*-
"""Ejercicio1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e-0CYa2XMeEUeMBpHJqI2BmYKf7rBci5
"""

import pandas as pd
import numpy as np
df = pd.read_csv('/content/drive/MyDrive/Datasets/winequality-red.csv')

"""Pongo en orden la base de datos"""

df=pd.DataFrame(np.sort(df.values,axis=0),index=df.index,columns=df.columns)
print(df)

df.describe()

"""Defino la media"""

def prom(v2):
  return sum(v2)/len(v2)

"""Ejemplo:"""

prom(df['fixed acidity'])

prom(df['quality'])

"""Defino la Moda:"""

def modales(v3):
  n=len(v3)
  contador1=0
  contador2=0
  for i in range(n):
    contador1=0
    for j in range(n):
      if(v3[i]==v3[j]):
        contador1 = contador1 +1 
    if(contador1>contador2):
      contador2=contador1
      modales=v3[i]
  print(modales)

"""Ejemplos:"""

modales(df['fixed acidity'])

modales(df['total sulfur dioxide'])

"""Defino el percentil. Tambien sirve para calcular los cuartiles, es decir P_25=Q_1, P_50=Q_2, P_75=Q_3. Ademas la mediana es igual a P_50"""

def percentil(v5,v4):
  x=((len(v4)*v5)/100)
  E=int(x)
  D=x-E
  if(D==0):
    percentil = ((v4[E-1]+v4[E])/2)
  else:
    percentil = v4[E]
  print(percentil)

"""Ejemplos:"""

percentil(25,df['residual sugar'])

percentil(50,df['residual sugar'])

percentil(75,df['residual sugar'])

percentil(10,df['residual sugar'])

"""Con Pandas

La media, cuartiles (25%,50%,75%):
"""

df.describe()

"""con describe en pandas los percentiles estan de 0.01 a 0.99"""

df.describe([.10])

"""Moda"""

fa = df['fixed acidity']

fa.mode()

"""En Numpy

Media
"""

np.mean(df['pH'])

"""Percentil van de 0 a 100"""

np.percentile(df['fixed acidity'],25)

"""Cuartiles van de 0 a 1"""

np.quantile(df['fixed acidity'],0.25)

