# -*- coding: utf-8 -*-
"""Ejercicio 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEdj-coQMl3k_oM88nSPiE982X5Nvl9Z
"""

!pip install kanren

from kanren import run, var, Relation, facts
x=var()
parent = Relation()
facts(parent,("Abuelo2","Madre"),("Abuelo2","Tia2"),
      ("Abuela2","Madre"), ("Abuela2","Tia2"),
      ("Abuelo1","Padre"),("Abuelo1","Tio1"),("Abuelo1","Tia1"),
      ("Abuela1","Padre"),("Abuela1","Tio1"),("Abuela1","Tia1"),
      ("Padre","Hijo"), ("Padre","Hija"), 
      ("Madre","Hijo"), ("Madre","Hija")
      ("Tio1","Primo1"), ("Tio1","Prima1"),
      ("Tia11","Primo1"), ("Tia11","Prima1"),)

"""Ejemplos:"""

run(2,x,parent(x,"Hijo"))

run(3,x,parent("Abuela1",x))

